/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

/**
 *
 * @author Maggie Zeta
 */
public class settings extends javax.swing.JFrame {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pengaturanLabel = new javax.swing.JLabel();
        tempatPenyimpananFileLabel = new javax.swing.JLabel();
        pluginTextField = new javax.swing.JTextField();
        pluginLabel = new javax.swing.JLabel();
        jsonButton = new javax.swing.JRadioButton();
        xmlButton = new javax.swing.JRadioButton();
        formatFileLabel = new javax.swing.JLabel();
        tempatPenyimpananFileTextField = new javax.swing.JTextField();
        tambahkanBaruButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pengaturanLabel.setFont(new java.awt.Font("Inter", 1, 33)); // NOI18N
        pengaturanLabel.setForeground(new java.awt.Color(229, 151, 0));
        pengaturanLabel.setText("Pengaturan");

        tempatPenyimpananFileLabel.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        tempatPenyimpananFileLabel.setForeground(new java.awt.Color(36, 60, 148));
        tempatPenyimpananFileLabel.setText("Tempat Penyimpanan File");

        pluginTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 79, 196), 2, true));
        pluginTextField.setPreferredSize(new java.awt.Dimension(440, 44));

        pluginLabel.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        pluginLabel.setForeground(new java.awt.Color(36, 60, 148));
        pluginLabel.setText("Plugin");

        jsonButton.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        jsonButton.setForeground(new java.awt.Color(36, 60, 148));
        jsonButton.setText("JSON");

        xmlButton.setFont(new java.awt.Font("Inter", 0, 15)); // NOI18N
        xmlButton.setForeground(new java.awt.Color(36, 60, 148));
        xmlButton.setText("XML");

        formatFileLabel.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        formatFileLabel.setForeground(new java.awt.Color(36, 60, 148));
        formatFileLabel.setText("Format File");

        tempatPenyimpananFileTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 79, 196), 2, true));
        tempatPenyimpananFileTextField.setPreferredSize(new java.awt.Dimension(440, 44));
        tempatPenyimpananFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatPenyimpananFileTextFieldActionPerformed(evt);
            }
        });

        tambahkanBaruButton.setBackground(new java.awt.Color(76, 110, 223));
        tambahkanBaruButton.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        tambahkanBaruButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahkanBaruButton.setText("+ Tambahkan Baru");
        tambahkanBaruButton.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tempatPenyimpananFileLabel)
                                        .addComponent(pengaturanLabel)
                                        .addComponent(pluginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pluginLabel)
                                        .addComponent(jsonButton)
                                        .addComponent(xmlButton)
                                        .addComponent(formatFileLabel)
                                        .addComponent(tempatPenyimpananFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tambahkanBaruButton))
                                .addGap(0, 450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(pengaturanLabel)
                                .addGap(18, 18, 18)
                                .addComponent(tempatPenyimpananFileLabel)
                                .addGap(20, 20, 20)
                                .addComponent(tempatPenyimpananFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(formatFileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsonButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xmlButton)
                                .addGap(18, 18, 18)
                                .addComponent(pluginLabel)
                                .addGap(18, 18, 18)
                                .addComponent(pluginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(tambahkanBaruButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void tempatPenyimpananFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel formatFileLabel;
    private javax.swing.JRadioButton jsonButton;
    private javax.swing.JLabel pengaturanLabel;
    private javax.swing.JLabel pluginLabel;
    private javax.swing.JTextField pluginTextField;
    private javax.swing.JButton tambahkanBaruButton;
    private javax.swing.JLabel tempatPenyimpananFileLabel;
    private javax.swing.JTextField tempatPenyimpananFileTextField;
    private javax.swing.JRadioButton xmlButton;
    // End of variables declaration
}
